SELECT
  sessions.id,
  sessions.user_id,
  sessions.birth_time,
  sessions.hashed_secret,
  sessions.user_agent_seen_first,
  sessions.row_start,
  sessions.row_end
FROM
  sessions
UNION
ALL
SELECT
  sessions_history.id,
  sessions_history.user_id,
  sessions_history.birth_time,
  sessions_history.hashed_secret,
  sessions_history.user_agent_seen_first,
  sessions_history.row_start,
  sessions_history.row_end
FROM
  sessions_history;