#!/usr/bin/env bash

set -eu -o pipefail

here=$(dirname -- "$0")

export DATABASE_URI=$(pg_tmp)
schema="$here"/../schema
psql -X "$DATABASE_URI" \
	-f "$schema"/extensions.sql \
	-f "$schema"/schema.sql
