CREATE EXTENSION IF NOT EXISTS periods VERSION '1.2' CASCADE;
-- GRANT USAGE ON SCHEMA periods TO cards;

CREATE EXTENSION IF NOT EXISTS pg_ivm VERSION '1.3' CASCADE;

CREATE EXTENSION IF NOT EXISTS pgroonga;
