#!/usr/bin/env bash

set -eu -o pipefail

here=$(dirname -- "$0")
schema=$here/../../../schema

export DATABASE_URL=$("$here"/prisma-compatible-postgres-uri "$(pg_tmp)")

psql -X "$DATABASE_URL" \
	-f "$schema"/extensions.sql \
	-f "$schema"/schema.sql
# TODO: insert some sample data

export SESSION_COOKIE_NAME=s
export SESSION_COOKIE_PATH=/
export SESSION_COOKIE_SECURE=0

./node_modules/.bin/vite dev --host
